### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'lower'

### ISSUE THREAD

**Issue by mbacvanski** [nunobrum/spicelib#116]
On MacOS, I'm getting an error 

```
AttributeError: 'PosixPath' object has no attribute 'lower'. Did you mean: 'owner'?
```

from this line: https://github.com/nunobrum/spicelib/blob/b49ef62c2bf6aece46afd5cc2ff95b9f2298b89e/spicelib/simulators/ltspice_simulator.py#L268

when I call `SimRunner(...).run(netlist)`.

This can be remedied by replacing it with
`if netlist_file.suffix.lower() == ".asc":`

**Comment by hb020** [comment]
Indeed, good catch. Will look if this problem is also elsewhere.

**Comment by nunobrum** [comment]
Integrated in version 1.3.2
