### ISSUE TITLE
Error SpiceEditor(filename.asc)

### ISSUE THREAD

**Issue by J-escandon** [nunobrum/spicelib#22]
When trying to perform: 

```
# Open the Spice Model, and creates the .net
netlist = SpiceEditor("myCircuit.asc")
```

as shown in the documentation I always get the error of:

`EncodingDetectError: Expected string "*" not found in file:myCircuit.asc`

I am coming from pyltspice and this was not a problem there. Is there something I am missing?

**Comment by nunobrum** [comment]
In spicelib you have to use the AscEditor instead. 
This avoids the need of creating a net file.

**Comment by nunobrum** [comment]
Closing this issue. Feel free to reopen it if my previous answer doesn't solve your problem.
