### ISSUE TITLE
Hardcoded server timeout

### ISSUE THREAD

**Issue by hakan-demirli** [nunobrum/spicelib#27]
Is it possible to expose hard codded timeout duration for server jobs.
https://github.com/nunobrum/spicelib/blob/ce7bb03a307323dd1fee91506668306914624056/spicelib/client_server/sim_server.py#L39

**Comment by nunobrum** [comment]
Yes. I'll include this in the next release. 

I'm working in a few new features, so I would bundle everything together. 
If all goes well, it's going to be within 2 weeks.

**Comment by nunobrum** [comment]
Version 1.0.0 corrects this issue.
