### ISSUE TITLE
Is it possible to set parasitic properties?

### ISSUE THREAD

**Issue by hakan-demirli** [nunobrum/spicelib#28]
For example series resistance and parallel capacitance of a voltage source.

**A workaround:**
Open the asc file on LTSpice and manualy put the parameters in place of parasitic values `{Rpar}`, `{Vpar}`. Then set these parameters using set_parameter method.

**Comment by nunobrum** [comment]
Yes. it is possible to use the set value to update every parameter of a voltage source.
You can even change a PWL definition. For example: the following is perfectly possible:
```python
LT.set_component_value("V1", "PWL(0, 0, 1m, 0, 1.001m 1)")  # Updates the PWM on V1
LT.set_component_value("V2", "4 Rser=1 Cpar=1u")  # Sets V2 to 4V with a 1Ohm series resistor and 1uF parallel capacitance
```
You see. The regular expression to update the voltage source, assumes as value everything that is after the two node terminals all the way to the end of the line.
'V': r"^(?P<designator>V§?\w+)(?P<nodes>(\s+\S+){2})\s+(?P<value>.*)$",  # Voltage Source

As long as you respect the LTSpice Voltage source syntax, everything is possible.
