### ISSUE TITLE
AscEditor.add_instruction() hangs

### ISSUE THREAD

**Issue by hb020** [nunobrum/spicelib#43]
Pretty simple one here:
Inside ```AscEditor.add_instruction```:
```python
            while i < len(self.directives):
                directive = self.directives[i]
                if directive.type == TextTypeEnum.COMMENT:
                    continue  # this is a comment
```
should become
```python
            while i < len(self.directives):
                directive = self.directives[i]
                if directive.type == TextTypeEnum.COMMENT:
                    i += 1
                    continue  # this is a comment
```

I could make  a PR, but this is so simple....

**Comment by nunobrum** [comment]
Thanks for your contribution. 
I agree that just for a simple thing, a PR is an overkill. 
I've already corrected it. See branch version-1.1.3
Will close this when the branch is merged back into main.
