### ISSUE TITLE
Lower log level of "INFO:spicelib.AsyReader:Parsing ASY file ....."

### ISSUE THREAD

**Issue by hb020** [nunobrum/spicelib#63]
This log level is too high to my taste. It generates a lot of log lines, without much info when all is OK.
Would it be OK to lower that to DEBUG?

**Comment by hb020** [comment]
ignoring, asceditor also has this.

**Comment by nunobrum** [comment]
We could lower the logging level down to DEBUG.
I kind of like it verbose though, especially when running from command line.
