### ISSUE TITLE
Symbol search in asceditor fails when symbol name has different casing than symbol file

### ISSUE THREAD

**Issue by hb020** [nunobrum/spicelib#68]
LTSpice treats all symbols case insensitive it seems, as we can have both

```
SYMBOL res 4912 -608 R90
SYMATTR InstName R2
....
SYMBOL Res 4208 -800 R90
SYMATTR InstName R3
```
in the .asc files. The asc_editor however fails on this, with 
```
  File "[redacted]/spicelib/spicelib/editor/asc_editor.py", line 249, in _get_symbol
    raise FileNotFoundError(f"File {asy_filename} not found")
FileNotFoundError: File Res.asy not found
```
on R3, while searching for "Res.asy". While R2 works, as the file is named "res.asy".
This is on MacOS, but Linux will surely suffer from this as well, and maybe even Windows.

Will provide a PR.

See branch [case-sensitivity-68](https://github.com/nunobrum/spicelib/tree/case-sensitivity-68)

**Comment by nunobrum** [comment]
Merged branch. Closing issue
