### ISSUE TITLE
.asy: SYMATTR Prefix is case senstitive

### ISSUE THREAD

**Issue by hb020** [nunobrum/spicelib#99]
Suppose a .asy file

With `SYMATTR Prefix x` (note: lowercase) => self._get_symbol().is_subcircuit() = False

With `SYMATTR Prefix X` (note: uppercase) => self._get_symbol().is_subcircuit() = True

(for `SymbolType CELL`)

**Comment by hb020** [comment]
The same problem was in .asc, so I adapted both sides.

**Comment by hb020** [comment]
This whole upper/lower case thing is wider, as a lot of comparisons in the code are case sensitive. But that is for later?

**Comment by hb020** [comment]
to be closed after release to PyPi.org

**Comment by nunobrum** [comment]
Scheduled for 1.3.0
